apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx-deployment-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynginx-blue
  template:
    metadata:
      labels:
        app: mynginx-blue
    spec:
      containers:
      - name: mynginx-container
        image: nginx:1.17.0
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: mynginx-service-blue
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: mynginx-blue

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-green
  template:
    metadata:
      labels:
        app: httpd-green
    spec:
      containers:
      - name: httpd-container
        image: httpd
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: httpd-service-green
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: mynginx-blue